# Generated by Django 3.1.1 on 2021-02-27 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('address', models.CharField(blank=True, default='Nigeria', max_length=101, null=True)),
                ('phoneNumber', models.CharField(default=123, max_length=11)),
                ('age', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUs', models.CharField(max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Address', models.CharField(default='Nigeria', max_length=101)),
                ('phoneNumber', models.CharField(default=123, max_length=11)),
                ('license', models.ImageField(default='Document.png', upload_to='Documents')),
                ('Frontview', models.ImageField(default='Hospital.jpg', upload_to='Hospital_pics')),
                ('Backview', models.ImageField(default='Hospital.jpg', upload_to='Hospital_pics')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('homeAddress', models.CharField(default='Nigeria', max_length=101)),
                ('workingAddress', models.CharField(default='Nigeria', max_length=101)),
                ('phoneNumber', models.CharField(default=123, max_length=11)),
                ('doc_cert', models.ImageField(default='Document.png', upload_to='Documents')),
                ('license', models.ImageField(default='Document.png', upload_to='Documents')),
                ('working_Hospital', models.CharField(max_length=150)),
                ('about_doc', models.TextField(default='Tell us About yourself Doc!')),
                ('specialty', models.CharField(default='Doctor', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('consultation_fee', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
