# Generated by Django 3.1.1 on 2021-03-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='workingAddress',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('Den', 'Dentist'), ('Pae', 'Peadetrician'), ('Car', 'Cardiologist'), ('Gyn', 'Gynacologist'), ('Doc', 'MedicalDoctor')], default='Doc', max_length=100),
        ),
    ]
